// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/transmitter/transmitter-contract.proto

package transmitter_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NewConnectionService_RandomDataGen_FullMethodName = "/transmitter.NewConnectionService/RandomDataGen"
)

// NewConnectionServiceClient is the client API for NewConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewConnectionServiceClient interface {
	RandomDataGen(ctx context.Context, in *VoidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NewConnectionResponse], error)
}

type newConnectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNewConnectionServiceClient(cc grpc.ClientConnInterface) NewConnectionServiceClient {
	return &newConnectionServiceClient{cc}
}

func (c *newConnectionServiceClient) RandomDataGen(ctx context.Context, in *VoidRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NewConnectionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NewConnectionService_ServiceDesc.Streams[0], NewConnectionService_RandomDataGen_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VoidRequest, NewConnectionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NewConnectionService_RandomDataGenClient = grpc.ServerStreamingClient[NewConnectionResponse]

// NewConnectionServiceServer is the server API for NewConnectionService service.
// All implementations must embed UnimplementedNewConnectionServiceServer
// for forward compatibility.
type NewConnectionServiceServer interface {
	RandomDataGen(*VoidRequest, grpc.ServerStreamingServer[NewConnectionResponse]) error
	mustEmbedUnimplementedNewConnectionServiceServer()
}

// UnimplementedNewConnectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewConnectionServiceServer struct{}

func (UnimplementedNewConnectionServiceServer) RandomDataGen(*VoidRequest, grpc.ServerStreamingServer[NewConnectionResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RandomDataGen not implemented")
}
func (UnimplementedNewConnectionServiceServer) mustEmbedUnimplementedNewConnectionServiceServer() {}
func (UnimplementedNewConnectionServiceServer) testEmbeddedByValue()                              {}

// UnsafeNewConnectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewConnectionServiceServer will
// result in compilation errors.
type UnsafeNewConnectionServiceServer interface {
	mustEmbedUnimplementedNewConnectionServiceServer()
}

func RegisterNewConnectionServiceServer(s grpc.ServiceRegistrar, srv NewConnectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedNewConnectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NewConnectionService_ServiceDesc, srv)
}

func _NewConnectionService_RandomDataGen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VoidRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NewConnectionServiceServer).RandomDataGen(m, &grpc.GenericServerStream[VoidRequest, NewConnectionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NewConnectionService_RandomDataGenServer = grpc.ServerStreamingServer[NewConnectionResponse]

// NewConnectionService_ServiceDesc is the grpc.ServiceDesc for NewConnectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewConnectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transmitter.NewConnectionService",
	HandlerType: (*NewConnectionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RandomDataGen",
			Handler:       _NewConnectionService_RandomDataGen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/transmitter/transmitter-contract.proto",
}
